# Generated by Django 2.2.17 on 2020-12-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='long_text_input_model_field_for_email_address',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='long_text_input_model_field_for_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
